apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: REPLACE_APP_NAME
spec:
  enableMetrics: false
  license:
    accept: true
    license: L-KSBM-C87FU2
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 150Mi
  adminServerSecure: false
  router:
    timeout: 120s
  barURL: 'REPLACE_WITH_BAR_URL_FROM_NEXUS'
  configurations:
  - nexus-creds
  - application.kdb
  - application.sth
  - mqtest-policyproject
  - mqtest-server.conf.yaml
  designerFlowsOperationMode: disabled
  createDashboardUsers: false
  service:
    endpointType: http
  version: '12.0.2.0-r2'
  replicas: 1
